# 导入两个库

In [1]:
import numpy as np 
import matplotlib.pyplot as plt

# 生成系数矩阵A和b

## 生成系数矩阵A

In [2]:
n=100    #定义阶数  PS：以下各算法不再修改n的值，均在此基础上进行。只需修改n的值再重新运行算法即可计算不同阶数的结果。

middle_array = np.empty(n, dtype=float)    #创建对角元数组
middle_array.fill(6)

upper_array = np.empty(n-1, dtype=float)   #创建上对角元数组
upper_array.fill(1)

down_array = np.empty(n-1, dtype=float)    #创建下对角元数组
down_array.fill(8)

A=np.diag(middle_array)+np.diag(upper_array,1)+np.diag(down_array,-1)  #生成矩阵A



## 生成矩阵b

In [3]:
b=np.full(
    shape=n,
    fill_value=15,
    dtype=float)
b[0]=7
b[n-1]=14

## 显示矩阵A, b规模和矩阵A, b

In [4]:
A.shape,b.shape

((100, 100), (100,))

In [5]:
A,b

(array([[6., 1., 0., ..., 0., 0., 0.],
        [8., 6., 1., ..., 0., 0., 0.],
        [0., 8., 6., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 6., 1., 0.],
        [0., 0., 0., ..., 8., 6., 1.],
        [0., 0., 0., ..., 0., 8., 6.]]),
 array([ 7., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.,
        15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.,
        15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.,
        15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.,
        15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.,
        15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.,
        15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.,
        15., 15., 15., 15., 15., 15., 15., 15., 14.]))

# 进行顺序Gauss消元法

In [6]:
row = A.shape[0]#记录A矩阵行数
col = A.shape[1]#记录A矩阵列数
row,col


(100, 100)

## 消去过程

In [7]:
for i in range(0, row):                         #从0到99行循环
        for j in range(i+1, col):               #将A矩阵第i行以下各行依次消去
            temp = A[j][i]/A[i][i]
            b[j]=b[j]-b[i] * temp               #将b矩阵各元素依此消去
            for k in range(0, col):
                A[j][k]=A[j][k]-A[i][k] * temp
                       

In [8]:
A,b        #显示徐消去后的矩阵A和b

(array([[6.        , 1.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.        , 4.66666667, 1.        , ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 4.28571429, ..., 0.        , 0.        ,
         0.        ],
        ...,
        [0.        , 0.        , 0.        , ..., 4.        , 1.        ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 4.        ,
         1.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         4.        ]]),
 array([ 7.00000000e+00,  5.66666667e+00,  5.28571429e+00,  5.13333333e+00,
         5.06451613e+00,  5.03174603e+00,  5.01574803e+00,  5.00784314e+00,
         5.00391389e+00,  5.00195503e+00,  5.00097704e+00,  5.00048840e+00,
         5.00024417e+00,  5.00012208e+00,  5.00006104e+00,  5.00003052e+00,
         5.00001526e+00,  5.00000763e+00,  5.00000381e+00,  5.00000191e+00,
         5.00000095e+00,  5.0

## 回代过程

In [9]:
x=np.empty(n, dtype=float)    #定义x空数组
x[row-1]=b[row-1]/A[row-1][row-1]    #从x[n-1]到x[0]依次回代求解
for i in range(row-2,-1,-1):   
    x[i]=b[i]/A[i][i]
    for j in range(i+1,row):
        x[i]=x[i]-A[i][j]*x[j]/A[i][i]

In [10]:
x        #显示线性方程组的解

array([ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
        1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
        1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
        1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
        1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
        1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
        9.99999998e-01,  1.00000000e+00,  9.99999993e-01,  1.00000001e+00,
        9.99999970e-01,  1.00000006e+00,  9.99999881e-01,  1.00000024e+00,
        9.99999523e-01,  1.00000095e+00,  9.99998093e-01,  1.00000381e+00,
        9.99992371e-01,  1.00001526e+00,  9.99969484e-01,  1.00006103e+00,
        9.99877937e-01,  1.00024413e+00,  9.99511749e-01,  1.00097650e+00,
        9.98046994e-01,  1.00390601e+00,  9.92187977e-01,  1.01562405e+00,
        9.68751907e-01,  1.06249619e+00,  8.75007629e-01,  1.24998474e+00,
        5.00030518e-01,  

-------
-------
-------

# 进行列主元Gauss消元法

## 重新生成矩阵A和b（矩阵A和b在上一问时已发生了改变）

In [11]:
A=np.diag(middle_array)+np.diag(upper_array,1)+np.diag(down_array,-1)
b=np.full(
    shape=n,
    fill_value=15,
    dtype=float)
b[0]=7
b[n-1]=14

## 显示矩阵A, b规模和矩阵A, b

In [12]:
A.shape,b.shape

((100, 100), (100,))

In [13]:
A,b

(array([[6., 1., 0., ..., 0., 0., 0.],
        [8., 6., 1., ..., 0., 0., 0.],
        [0., 8., 6., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 6., 1., 0.],
        [0., 0., 0., ..., 8., 6., 1.],
        [0., 0., 0., ..., 0., 8., 6.]]),
 array([ 7., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.,
        15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.,
        15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.,
        15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.,
        15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.,
        15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.,
        15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.,
        15., 15., 15., 15., 15., 15., 15., 15., 14.]))

# 进行列主元Gauss消元法

In [14]:
row = A.shape[0]#记录A矩阵行数
col = A.shape[1]#记录A矩阵列数
row,col

(100, 100)

## 消去过程

In [15]:
for i in range(0, row):                         #行循环
        for j in range(i+1, col):
            if abs(A[j][i]) > abs(A[i][i]):
                t = np.copy(A[i])
                A[i] = A[j]
                A[j] = t      
                t = b[i]
                b[i] = b[j]
                b[j] = t

        for j in range(i+1, col):               #将A矩阵第i列的下三角部分消为0
            temp = A[j][i]/A[i][i]
            b[j]=b[j]-b[i] * temp               #将b矩阵各元素依此消去
            for k in range(0, col):
                A[j][k]=A[j][k]-A[i][k] * temp    

                

In [16]:
A,b        #显示徐消去后的矩阵A和b

(array([[ 8.00000000e+00,  6.00000000e+00,  1.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  8.00000000e+00,  6.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  8.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        ...,
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          8.00000000e+00,  6.00000000e+00,  1.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  8.00000000e+00,  6.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00, -1.26217745e-29]]),
 array([ 1.50000000e+01,  1.50000000e+01,  1.50000000e+01,  1.50000000e+01,
         1.50000000e+01,  1.50000000e+01,  1.50000000e+01,  1.50000000e+01,
         1.50000000e+01,  1.50000000e+01,  1.50000000e+01,  1.50000000e+01,
 

## 回代过程

In [17]:
x=np.empty(n, dtype=float)       #定义x空数组
x[row-1]=b[row-1]/A[row-1][row-1]
for i in range(row-2,-1,-1):       #从x[n-1]到x[0]依次回代求解
    x[i]=b[i]/A[i][i]
    for j in range(i+1,row):
        x[i]=x[i]-A[i][j]*x[j]/A[i][i]

In [18]:
x        #显示线性方程组的解

array([1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 0.99999999, 1.00000

------
-------
------

# 进行追赶法

## 重新生成矩阵A和b（矩阵A和b在上一问时已发生了改变）

In [19]:
A=np.diag(middle_array)+np.diag(upper_array,1)+np.diag(down_array,-1)
b=np.full(
    shape=n,
    fill_value=15,
    dtype=float)
b[0]=7
b[n-1]=14

## 显示矩阵A, b规模和矩阵A, b

In [20]:
A.shape,b.shape

((100, 100), (100,))

In [21]:
A,b

(array([[6., 1., 0., ..., 0., 0., 0.],
        [8., 6., 1., ..., 0., 0., 0.],
        [0., 8., 6., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 6., 1., 0.],
        [0., 0., 0., ..., 8., 6., 1.],
        [0., 0., 0., ..., 0., 8., 6.]]),
 array([ 7., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.,
        15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.,
        15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.,
        15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.,
        15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.,
        15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.,
        15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.,
        15., 15., 15., 15., 15., 15., 15., 15., 14.]))

## 进行追赶法

In [22]:
a1 = np.insert(down_array,0,0)  #创建a数组，第一位补0
b1 = middle_array               #创建b数组，由于已使用b数组，这里用b1替代，a1、c1同理
c1 = np.insert(upper_array,n-1,0)         #创建c数组,最后一位补0

In [23]:
a1,b1,c1   #显示三个数组

(array([0., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.,
        8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.,
        8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.,
        8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.,
        8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.,
        8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]),
 array([6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.,
        6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.,
        6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.,
        6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.,
        6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.,
        6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 

In [24]:
y = np.zeros(n)
B = np.zeros(n)
x = np.zeros(n)

In [25]:
y[0] = b[0] / b1[0]
d = b1[0]    #α[0]

### 追

In [26]:
for i in range(1, n):
    B[i - 1] = c1[i - 1] / d
    d = b1[i] - a1[i] * B[i - 1]   #α不再另创数组，每次循环修改值
    y[i] = (b[i] - a1[i] * y[i - 1]) / d
x[n-1] = y[n-1]

### 赶

In [27]:
for i in range(n-2, -1, -1):
    x[i] = y[i] - B[i] * x[i + 1]

In [28]:
x        #显示线性方程组的解

array([ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
        1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
        1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
        1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
        1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
        1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  9.99999999e-01,
        1.00000000e+00,  9.99999996e-01,  1.00000001e+00,  9.99999985e-01,
        1.00000003e+00,  9.99999940e-01,  1.00000012e+00,  9.99999762e-01,
        1.00000048e+00,  9.99999046e-01,  1.00000191e+00,  9.99996186e-01,
        1.00000763e+00,  9.99984742e-01,  1.00003052e+00,  9.99938969e-01,
        1.00012206e+00,  9.99755874e-01,  1.00048825e+00,  9.99023497e-01,
        1.00195301e+00,  9.96093988e-01,  1.00781202e+00,  9.84375954e-01,
        1.03124809e+00,  9.37503815e-01,  1.12499237e+00,  7.50015259e-01,
        1.49996948e+00,  

------
------
------

# Jacobi迭代法

## 显示矩阵A, b规模和矩阵A, b。
## 此时不需重新生成矩阵，矩阵A,b在追赶法中未改变。

In [29]:
A.shape,b.shape

((100, 100), (100,))

In [30]:
A,b

(array([[6., 1., 0., ..., 0., 0., 0.],
        [8., 6., 1., ..., 0., 0., 0.],
        [0., 8., 6., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 6., 1., 0.],
        [0., 0., 0., ..., 8., 6., 1.],
        [0., 0., 0., ..., 0., 8., 6.]]),
 array([ 7., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.,
        15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.,
        15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.,
        15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.,
        15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.,
        15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.,
        15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.,
        15., 15., 15., 15., 15., 15., 15., 15., 14.]))

## 进行Jacobi迭代

In [31]:
x=np.zeros(shape=(n,100))  #创建x空矩阵，第几列代表第几次迭代的值，初值都取为0
x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [32]:
# 以分量形式进行Jacobi迭代
for k in range(1, 100):  #循环迭代，迭代99次
    for i in range(0, n):
        x[i][k]=b[i]/A[i][i]
        for j in range(0, i):
            x[i][k]=x[i][k]-A[i][j] * x[j][k-1]/A[i][i]
        for j in range(i+1, n):
            x[i][k]=x[i][k]-A[i][j] * x[j][k-1]/A[i][i]

In [33]:
x   #显示x矩阵

array([[ 0.00000000e+00,  1.16666667e+00,  7.50000000e-01, ...,
         1.00000482e+00,  9.99992777e-01,  1.00000416e+00],
       [ 0.00000000e+00,  2.50000000e+00,  5.27777778e-01, ...,
         1.00004334e+00,  9.99975063e-01,  1.00003741e+00],
       [ 0.00000000e+00,  2.50000000e+00, -1.25000000e+00, ...,
         1.00011110e+00,  9.99833356e-01,  1.00009596e+00],
       ...,
       [ 0.00000000e+00,  2.50000000e+00, -1.25000000e+00, ...,
         1.20227293e+17, -1.80339185e+17,  2.70508778e+17],
       [ 0.00000000e+00,  2.50000000e+00, -1.22222222e+00, ...,
         1.18580343e+17, -1.77870515e+17,  2.66803434e+17],
       [ 0.00000000e+00,  2.33333333e+00, -1.00000000e+00, ...,
         1.05404750e+17, -1.58107125e+17,  2.37160687e+17]])

In [34]:
x[:,99] #显示迭代99次后的结果

array([1.00000416e+00, 1.00003741e+00, 1.00009596e+00, 1.00056435e+00,
       1.00118393e+00, 1.00614057e+00, 1.01180310e+00, 1.05710334e+00,
       1.10393834e+00, 1.47861834e+00, 1.83677160e+00, 4.70199770e+00,
       7.26359435e+00, 2.77563675e+01, 4.50097731e+01, 1.83037017e+02,
       2.92950730e+02, 1.17226043e+03, 1.83644986e+03, 7.14996531e+03,
       1.09644865e+04, 4.14806560e+04, 6.23288966e+04, 2.29114822e+05,
       3.37647830e+05, 1.20591190e+06, 1.74437712e+06, 6.05209892e+06,
       8.59886080e+06, 2.89729558e+07, 4.04570850e+07, 1.32330118e+08,
       1.81699571e+08, 5.76655188e+08, 7.78946677e+08, 2.39727859e+09,
       3.18706224e+09, 9.50533146e+09, 1.24419654e+10, 3.59350369e+10,
       4.63283170e+10, 1.29474558e+11, 1.64462433e+11, 4.44365438e+11,
       5.56308271e+11, 1.45185093e+12, 1.79193770e+12, 4.51263180e+12,
       5.49267612e+12, 1.33330307e+13, 1.60088425e+13, 3.74153368e+13,
       4.43280664e+13, 9.96299028e+13, 1.16502864e+14, 2.51486557e+14,
      

------
------
------

# Gauss-Seidel迭代法

## 显示矩阵A, b规模和矩阵A, b。
## 此时不需重新生成矩阵，矩阵A,b在上一问中未改变。

In [35]:
A.shape,b.shape

((100, 100), (100,))

In [36]:
A,b

(array([[6., 1., 0., ..., 0., 0., 0.],
        [8., 6., 1., ..., 0., 0., 0.],
        [0., 8., 6., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 6., 1., 0.],
        [0., 0., 0., ..., 8., 6., 1.],
        [0., 0., 0., ..., 0., 8., 6.]]),
 array([ 7., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.,
        15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.,
        15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.,
        15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.,
        15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.,
        15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.,
        15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.,
        15., 15., 15., 15., 15., 15., 15., 15., 14.]))

## 进行Gauss-Seidel迭代

In [37]:
x=np.zeros(shape=(n,100)) #创建x空矩阵，第几列代表第几次迭代的值，初值都取为0
x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [38]:
#以分量形式进行Jacobi迭代
for k in range(1, 100):   #循环迭代，迭代99次
    for i in range(0, n): 
        x[i][k]=b[i]/A[i][i]
        for j in range(0, i):
            x[i][k]=x[i][k]-A[i][j] * x[j][k]/A[i][i]
        for j in range(i+1, n):
            x[i][k]=x[i][k]-A[i][j] * x[j][k-1]/A[i][i]

In [39]:
x    #显示x矩阵

array([[ 0.00000000e+00,  1.16666667e+00,  1.00925926e+00, ...,
         1.00000000e+00,  1.00000000e+00,  1.00000000e+00],
       [ 0.00000000e+00,  9.44444444e-01,  9.47530864e-01, ...,
         9.99999997e-01,  9.99999997e-01,  9.99999997e-01],
       [ 0.00000000e+00,  1.24074074e+00,  1.09567901e+00, ...,
         1.00000001e+00,  1.00000001e+00,  1.00000001e+00],
       ...,
       [ 0.00000000e+00, -1.25276079e+11, -2.71928632e+12, ...,
        -3.10896022e+26, -3.07514128e+26, -3.03666579e+26],
       [ 0.00000000e+00,  1.67034772e+11,  3.66283393e+12, ...,
         5.34305290e+26,  5.28753346e+26,  5.22389516e+26],
       [ 0.00000000e+00, -2.22713029e+11, -4.88377857e+12, ...,
        -7.12407053e+26, -7.05004461e+26, -6.96519355e+26]])

In [40]:
x[:,99] #显示迭代99次后的结果

array([ 1.00000000e+00,  9.99999997e-01,  1.00000001e+00,  9.99999965e-01,
        1.00000011e+00,  9.99999649e-01,  1.00000105e+00,  9.99996932e-01,
        1.00000878e+00,  9.99975322e-01,  1.00006841e+00,  9.99812746e-01,
        1.00050686e+00,  9.98641799e-01,  1.00360603e+00,  9.90507135e-01,
        1.02479289e+00,  9.35725851e-01,  1.16546656e+00,  5.76835811e-01,
        2.07540417e+00, -1.71657176e+00,  7.82285108e+00, -1.60413043e+01,
        4.33369147e+01, -1.03639086e+02,  2.58335002e+02, -6.28795727e+02,
        1.53511152e+03, -3.71885804e+03,  8.98065840e+03, -2.15816872e+04,
        5.16555460e+04, -1.23114062e+05,  2.92250104e+05, -6.90989469e+05,
        1.62743453e+06, -3.81839024e+06,  8.92556160e+06, -2.07873391e+07,
        4.82391584e+07, -1.11548986e+08,  2.57053338e+08, -5.90334341e+08,
        1.35118408e+09, -3.08245117e+09,  7.00915705e+09, -1.58871189e+10,
        3.58967712e+10, -8.08568695e+10,  1.81572261e+11, -4.06510945e+11,
        9.07410255e+11, -